site_name: "TP expérimentations"
site_author: "FIL"
copyright: FIL
theme:
  name: "material"

nav:
  - Rendu: index.md
  - Experience documentation: experience.md
  - Marker documentation: marker.md
  - Sorting documentation: sorting.md
  
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        rendering:
          show_source: no
        setup_commands:
          - import sys
          - sys.path.append('src/')
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://www.fil.univ-lille.fr/~salson/portail/mathjax_conf.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
